master : Replaced India Country Flag and Added Shadow in Short Description Text
SEAbdulbasit/TravelApp-KMP pull request #14
Opened 2024-02-06 05:03 UTC by abhishektiwarijr

1. Replaced India Country Flag 
2. Added Shadow in Short Description Text - This made text more readable, Please let me know if this is acceptable.
3. Integration tested on Emulator (Android) and Web (Chrome).

2024-02-06 05:06 UTC, SEAbdulbasit commented
@abhishektiwarijr can you add a screenshot?

2024-02-06 05:13 UTC, abhishektiwarijr commented
> @abhishektiwarijr can you add a screenshot?

Added. Let me know if this is acceptable for the time being.

2024-02-06 16:01 UTC, SEAbdulbasit commented
I have added a gray layer. I think shadow will not look good.

![image](https://github.com/SEAbdulbasit/TravelApp-KMP/assets/33172684/d936bffc-68e4-4c5e-8ca0-07e1302f36e0)

2024-02-06 16:03 UTC, SEAbdulbasit requested changes

2024-02-06 16:03 UTC, SEAbdulbasit commented on shared/src/commonMain/composeResources/drawable/flag_india.png
Should we remove this one then?

2024-02-06 16:03 UTC, SEAbdulbasit commented on shared/src/commonMain/kotlin/com/example/travelapp_kmp/listing/MainScreen.kt
I have added a gray layer

2024-02-06 17:05 UTC, abhishektiwarijr commented on shared/src/commonMain/kotlin/com/example/travelapp_kmp/listing/MainScreen.kt
This looks better.

2024-02-06 17:07 UTC, abhishektiwarijr commented on shared/src/commonMain/composeResources/drawable/flag_india.png
The current Indian flag icon is blurred so that is why I replaced that icon with this https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/drawable/flag_india.png

Either I give you an updated PR or you can replace existing icon with this one.

2024-02-07 06:02 UTC, SEAbdulbasit commented on shared/src/commonMain/composeResources/drawable/flag_india.png
This one is also fine. Update the icon only and we can merge that.

2024-02-07 06:13 UTC, SEAbdulbasit commented
I have updated the PNG. It is now live: https://seabdulbasit.github.io/TravelApp-KMP/

2024-02-07 09:00 UTC, abhishektiwarijr commented
> I have updated the PNG. It is now live: https://seabdulbasit.github.io/TravelApp-KMP/

Awesome. Thanks man. So we can discard this PR.

2024-02-07 09:24 UTC, closed without merging